### ISSUE TITLE
latest update of optitype fails with an error

### ISSUE THREAD

**Issue by ksenia-krasheninnikova** [jj-umn/galaxytools#2]
Hello,

Optitype package (toolshed.g2.bx.psu.edu/repos/jjohnson/optitype/optitype/1.3.2) was installed into a local galaxy server from the toolshed. It was run on the paired-end data in the DNA mode and failed with the following error:

Traceback (most recent call last):
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/bin/OptiTypePipeline.py", line 129, in
from model import OptiType
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/share/optitype-1.3.2-3/model.py", line 19, in
from pyomo.environ import ConcreteModel, Set, Param, Var, Binary, Objective, Constraint, ConstraintList, maximize
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/init.py", line 97, in
_import_packages()
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/init.py", line 81, in _import_packages
raise ImportError(msg)
ImportError: pyomo.environ failed to import pyomo.core.plugins:
Original ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
Traceback:
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/init.py", line 69, in _import_packages
_do_import(pname)
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/init.py", line 19, in _do_import
import(pkg_name, globals(), locals(), [], -1)
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/init.py", line 11, in
from pyomo.core.expr import *
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/expr/init.py", line 36, in
from .calculus.derivatives import differentiate
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in
from pyutilib.enum import Enum
File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyutilib/enum/init.py", line 18, in
package) that supersedes this library.""")

A fix or possible solution would be most appreciated.

Thank you!

Best regards,

Ksenia

**Comment by jj-umn** [comment]
@ksenia-krasheninnikova   Sorry, I haven't had the time to work on this issue.   I hope to check on this in the next few weeks.  We have a researcher at University of Minnesota that considers optitype results as more reliable than seqHLA for some patients.

**Comment by ksenia-krasheninnikova** [comment]
OK good to know. Thank you for this information. Looking forward to the updates.

**Comment by jj-umn** [comment]
@ksenia-krasheninnikova I've updated Optitype to use version 1.3.5 and that has fixed issues for me.   Can you let me know if the newer version works for you?  Thanks.
